[project]
name = "marker"
version = "2.0.0"
description = "Marker converts documents to markdown, JSON, and HTML quickly and accurately."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "marker-pdf[full]==2.0.0",
    "surya-ocr==0.22.1",
    "python-multipart",
    "starlette",
    "torch>=2.7.0",
    "torchvision",
    "torchaudio",
    "uvicorn",
]

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
