[project]
name = "marker"
version = "1.10.2"
description = "Marker converts documents to markdown, JSON, and HTML quickly and accurately."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "marker-pdf[full]==1.10.2",
    "surya-ocr==0.17.1",
    "python-multipart",
    "starlette",
    "torch>=2.7.0",
    "torchvision",
    "torchaudio",
    "uvicorn",
]

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
